version: '3.8'

services:
  app:
    build: .
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=appusr
      - DB_PASSWORD=apppass
      - DB_NAME=school_system
      - SERVER_PORT=3004
      - SERVER_HOST=0.0.0.0  # Importante para conexiones externas
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: school_system
      MYSQL_USER: appusr
      MYSQL_PASSWORD: apppass
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: